name: Test
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip install -r test_requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        pytest -v --junitxml=rspec.xml --cov-report=html --cov=geomapi .