name: Test
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        cache: 'pip' # caching pip dependencies
    - name: Install dependencies
      run: |
        pip install -r tests/test_requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        pytest -v --junitxml=rspec.xml --cov-report=html --cov=geomapi coverage/
    - name: Upload Coverage Results
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: |
          ./coverage  # Adjust the path based on your coverage file location
      if: always()  # Upload coverage results even if tests fail
