name: Test
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        cache: 'pip' # caching pip dependencies
    - name: Install dependencies
      run: |
        pip install -r tests/test_requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        pytest -v --cov-report term --cov-report xml --cov=geomapi tests/
    - name: Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.xml
      if: always()  # Upload coverage results even if tests fail
